use std::{
    fs,
    path::{Component, Path, PathBuf},
};

use anyhow::{Context, Result, bail};
use rusqlite::{Connection, params};

use crate::{
    models::{MemoryPath, MemoryRecord, MemoryType, ScopeKind},
    search::{load_paths, record_from_row},
};

pub fn export_okf(conn: &Connection, destination: &Path, scope: ScopeKind) -> Result<Vec<PathBuf>> {
    let records = active_records_for_scope(conn, scope, None)?;
    export_records(conn, destination, &records)
}

pub fn export_agents_md(
    conn: &Connection,
    destination: &Path,
    scope: ScopeKind,
) -> Result<PathBuf> {
    export_instruction_projection(conn, destination, scope, "AGENTS.md")
}

pub fn export_claude_md(
    conn: &Connection,
    destination: &Path,
    scope: ScopeKind,
) -> Result<PathBuf> {
    export_instruction_projection(conn, destination, scope, "CLAUDE.md")
}

fn export_instruction_projection(
    conn: &Connection,
    destination: &Path,
    scope: ScopeKind,
    agent_name: &str,
) -> Result<PathBuf> {
    ensure_no_parent_traversal(destination)?;
    let records = active_records_for_scope(
        conn,
        scope,
        Some(&[
            MemoryType::Procedure,
            MemoryType::Decision,
            MemoryType::Warning,
            MemoryType::Risk,
        ]),
    )?;
    let mut output = String::from("<!-- Generated by memzoi. Do not edit directly. -->\n");
    output.push_str(&format!("# Memzoi Projection for {agent_name}\n\n"));
    output.push_str("This file is generated from active canonical memory records.\n\n");

    for record in &records {
        let paths = load_paths(conn, &record.id)?;
        output.push_str(&format!(
            "## {} [{}]\n\n",
            record.title,
            record.memory_type.as_str()
        ));
        output.push_str(&format!("Record: `{}`\n\n", record.id));
        if !paths.is_empty() {
            output.push_str("Applies to:\n");
            for path in paths {
                output.push_str(&format!("- `{}`\n", path.path));
            }
            output.push('\n');
        }
        output.push_str(&record.body);
        output.push_str("\n\n");
    }

    if let Some(parent) = destination.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create export directory {}", parent.display()))?;
    }
    fs::write(destination, output)
        .with_context(|| format!("failed to write projection {}", destination.display()))?;
    Ok(destination.to_path_buf())
}

fn export_records(
    conn: &Connection,
    destination: &Path,
    records: &[MemoryRecord],
) -> Result<Vec<PathBuf>> {
    ensure_no_parent_traversal(destination)?;
    fs::create_dir_all(destination).with_context(|| {
        format!(
            "failed to create export directory {}",
            destination.display()
        )
    })?;
    let mut written = Vec::with_capacity(records.len());
    for record in records {
        let paths = load_paths(conn, &record.id)?;
        let path = destination.join(format!("{}.md", safe_file_stem(&record.id)));
        fs::write(&path, render_record_markdown(record, &paths))
            .with_context(|| format!("failed to write export {}", path.display()))?;
        written.push(path);
    }
    Ok(written)
}

fn active_records_for_scope(
    conn: &Connection,
    scope: ScopeKind,
    memory_types: Option<&[MemoryType]>,
) -> Result<Vec<MemoryRecord>> {
    let mut sql = String::from(
        "SELECT id, type, lane, scope_kind, scope_id, visibility, title, body, status, confidence,
                source_kind, source_ref, content_hash, created_at, updated_at, supersedes_id,
                expires_at
         FROM memory_record
         WHERE status = 'active'
           AND scope_kind = ?1
           AND visibility != 'private'",
    );
    if let Some(types) = memory_types
        && !types.is_empty()
    {
        let quoted = types
            .iter()
            .map(|memory_type| format!("'{}'", memory_type.as_str()))
            .collect::<Vec<_>>()
            .join(", ");
        sql.push_str(&format!(" AND type IN ({quoted})"));
    }
    sql.push_str(" ORDER BY type ASC, title ASC, id ASC");

    let mut stmt = conn.prepare(&sql)?;
    let rows = stmt.query_map(params![scope.as_str()], record_from_row)?;
    Ok(rows.collect::<rusqlite::Result<Vec<_>>>()?)
}

fn render_record_markdown(record: &MemoryRecord, paths: &[MemoryPath]) -> String {
    let mut output = String::new();
    output.push_str("---\n");
    push_frontmatter(&mut output, "id", &record.id);
    push_frontmatter(&mut output, "type", record.memory_type.as_str());
    push_frontmatter(&mut output, "lane", record.lane.as_str());
    push_frontmatter(&mut output, "scope_kind", record.scope_kind.as_str());
    if let Some(scope_id) = &record.scope_id {
        push_frontmatter(&mut output, "scope_id", scope_id);
    }
    push_frontmatter(&mut output, "visibility", record.visibility.as_str());
    push_frontmatter(&mut output, "status", record.status.as_str());
    push_frontmatter(&mut output, "confidence", &record.confidence.to_string());
    if let Some(source_kind) = &record.source_kind {
        push_frontmatter(&mut output, "source_kind", source_kind);
    }
    if let Some(source_ref) = &record.source_ref {
        push_frontmatter(&mut output, "source_ref", source_ref);
    }
    push_frontmatter(&mut output, "content_hash", &record.content_hash);
    push_frontmatter(&mut output, "created_at", &record.created_at);
    push_frontmatter(&mut output, "updated_at", &record.updated_at);
    if let Some(supersedes_id) = &record.supersedes_id {
        push_frontmatter(&mut output, "supersedes_id", supersedes_id);
    }
    if let Some(expires_at) = &record.expires_at {
        push_frontmatter(&mut output, "expires_at", expires_at);
    }
    if !paths.is_empty() {
        output.push_str("applies_to:\n");
        for path in paths {
            output.push_str(&format!("  - {}\n", quote(&path.path)));
        }
    }
    output.push_str("---\n\n");
    output.push_str(&format!("# {}\n\n", record.title));
    output.push_str(&record.body);
    output.push('\n');
    output
}

fn push_frontmatter(output: &mut String, key: &str, value: &str) {
    output.push_str(key);
    output.push_str(": ");
    output.push_str(&quote(value));
    output.push('\n');
}

fn quote(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn ensure_no_parent_traversal(destination: &Path) -> Result<()> {
    if destination
        .components()
        .any(|component| matches!(component, Component::ParentDir))
    {
        bail!(
            "export destination must not contain parent traversal: {}",
            destination.display()
        );
    }
    Ok(())
}

fn safe_file_stem(id: &str) -> String {
    id.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use std::fs;

    use rusqlite::{Connection, params};
    use tempfile::TempDir;

    use super::{export_agents_md, export_okf};
    use crate::{
        init_database,
        models::{MemoryStatus, MemoryType, ScopeKind},
        open_database,
    };

    #[test]
    fn export_okf_writes_deterministic_active_markdown_records() -> anyhow::Result<()> {
        let (temp, conn) = initialized_database()?;
        insert_memory(
            &conn,
            "rec-active",
            MemoryType::Decision,
            ScopeKind::Repo,
            MemoryStatus::Active,
            "Repo decision",
            "Use the local memory index.",
            "crates/core/src/lib.rs",
        )?;
        insert_memory(
            &conn,
            "rec-personal",
            MemoryType::Fact,
            ScopeKind::Personal,
            MemoryStatus::Active,
            "Personal fact",
            "Do not export into repo scope.",
            "notes/private.md",
        )?;
        insert_memory(
            &conn,
            "rec-tombstone",
            MemoryType::Decision,
            ScopeKind::Repo,
            MemoryStatus::Tombstoned,
            "Old decision",
            "Inactive records are skipped.",
            "crates/core/src/old.rs",
        )?;

        let destination = temp.path().join("exports").join("okf");
        let first = export_okf(&conn, &destination, ScopeKind::Repo)?;
        let first_content = fs::read_to_string(&first[0])?;
        let second = export_okf(&conn, &destination, ScopeKind::Repo)?;
        let second_content = fs::read_to_string(&second[0])?;

        assert_eq!(first.len(), 1);
        assert_eq!(first_content, second_content);
        assert!(first_content.contains("id: \"rec-active\""));
        assert!(first_content.contains("applies_to:"));
        assert!(!first_content.contains("rec-personal"));
        assert!(!first_content.contains("rec-tombstone"));
        Ok(())
    }

    #[test]
    fn export_agents_projection_includes_instruction_types_only() -> anyhow::Result<()> {
        let (temp, conn) = initialized_database()?;
        insert_memory(
            &conn,
            "rec-procedure",
            MemoryType::Procedure,
            ScopeKind::Repo,
            MemoryStatus::Active,
            "Build procedure",
            "Run cargo test before reporting success.",
            "crates/core/src/lib.rs",
        )?;
        insert_memory(
            &conn,
            "rec-fact",
            MemoryType::Fact,
            ScopeKind::Repo,
            MemoryStatus::Active,
            "Background fact",
            "This should stay out of agent projections.",
            "docs/fact.md",
        )?;

        let destination = temp.path().join("AGENTS.memory.md");
        let written = export_agents_md(&conn, &destination, ScopeKind::Repo)?;
        let content = fs::read_to_string(written)?;

        assert!(content.contains("Generated by memzoi"));
        assert!(content.contains("rec-procedure"));
        assert!(content.contains("Run cargo test"));
        assert!(!content.contains("rec-fact"));
        Ok(())
    }

    #[test]
    fn export_okf_rejects_destination_with_parent_traversal() -> anyhow::Result<()> {
        let (temp, conn) = initialized_database()?;
        insert_memory(
            &conn,
            "rec-active",
            MemoryType::Decision,
            ScopeKind::Repo,
            MemoryStatus::Active,
            "Repo decision",
            "Keep exports confined.",
            "crates/core/src/lib.rs",
        )?;

        let exports_dir = temp.path().join("exports");
        let outside_dir = temp.path().join("outside");
        let traversal_destination = exports_dir.join("..").join("outside");

        let error = export_okf(&conn, &traversal_destination, ScopeKind::Repo)
            .expect_err("parent traversal must not be allowed for export destinations");

        assert!(
            error
                .to_string()
                .contains("export destination must not contain parent traversal"),
            "unexpected error: {error:#}"
        );
        assert!(
            !outside_dir.exists(),
            "export must not create directories outside the export root"
        );

        Ok(())
    }

    fn initialized_database() -> anyhow::Result<(TempDir, Connection)> {
        let temp = TempDir::new()?;
        let db_path = temp.path().join("memory.db");
        let conn = open_database(&db_path)?;
        init_database(&conn)?;
        Ok((temp, conn))
    }

    #[allow(clippy::too_many_arguments)]
    fn insert_memory(
        conn: &Connection,
        id: &str,
        memory_type: MemoryType,
        scope_kind: ScopeKind,
        status: MemoryStatus,
        title: &str,
        body: &str,
        path: &str,
    ) -> anyhow::Result<()> {
        conn.execute(
            "INSERT INTO memory_record(
                id, type, scope_kind, visibility, title, body, status, confidence,
                source_kind, source_ref, content_hash
             ) VALUES (?1, ?2, ?3, 'repo', ?4, ?5, ?6, 0.92, 'test', ?7, ?8)",
            params![
                id,
                memory_type.as_str(),
                scope_kind.as_str(),
                title,
                body,
                status.as_str(),
                format!("test://{id}"),
                format!("hash-{id}"),
            ],
        )?;
        conn.execute(
            "INSERT INTO memory_path(id, record_id, path, line_start, line_end)
             VALUES (?1, ?2, ?3, 1, 12)",
            params![format!("path-{id}"), id, path],
        )?;
        Ok(())
    }
}
