use std::{ops::Range, path::Path};

use anyhow::{Result, bail};

use super::{line_number_at, source_lines};
use crate::{MemoryDestination, MemoryLane, MemoryType, OkfProposalSensitivity, ScopeKind};

use super::super::{
    CaptureDiagnostic, CaptureExtraction, CaptureExtractorIdentity, CaptureMemoryDraft,
    CapturePlanningControl, CaptureScope, CaptureSemanticLocation, CaptureSourceDocument,
    EvidenceLocation, candidate, check_planning_control, contains_instruction_review_marker,
    evidence_for, markdown_sections,
};

const MEMZOI_START: &str = "<!-- memzoi:start -->";
const MEMZOI_END: &str = "<!-- memzoi:end -->";
const GENERATED_PROJECTION_HEADER: &str = "<!-- Generated by memzoi. Do not edit directly. -->";

pub(super) fn mask_generated_markers_for_scan(bytes: &[u8]) -> Vec<u8> {
    let mut masked = bytes.to_vec();
    for marker in [MEMZOI_START.as_bytes(), MEMZOI_END.as_bytes()] {
        let mut from = 0usize;
        while from + marker.len() <= masked.len() {
            let Some(relative) = masked[from..]
                .windows(marker.len())
                .position(|window| window == marker)
            else {
                break;
            };
            let start = from + relative;
            masked[start..start + marker.len()].fill(b' ');
            from = start + marker.len();
        }
    }
    masked
}

pub(super) fn extract(
    document: &CaptureSourceDocument,
    extractor: &CaptureExtractorIdentity,
    control: Option<&CapturePlanningControl>,
) -> Result<CaptureExtraction> {
    check_planning_control(control)?;
    let text = std::str::from_utf8(&document.bytes)?;
    if text.trim_start().starts_with(GENERATED_PROJECTION_HEADER) {
        return Ok(CaptureExtraction {
            candidates: Vec::new(),
            diagnostics: vec![CaptureDiagnostic {
                code: "generated_projection_excluded".to_owned(),
                source_id: Some(document.request.source_id.clone()),
                line: Some(1),
            }],
        });
    }

    let exclusions = generated_ranges(text)?;
    let masked = mask_ranges(text, &exclusions);
    let sections = markdown_sections(&masked, control)?;
    let scope = instruction_scope(document);
    let mut candidates = Vec::new();
    let mut diagnostics = Vec::new();

    let preamble_end = sections
        .first()
        .map(|section| section.start)
        .unwrap_or(text.len());
    let preamble = visible_text(text, 0..preamble_end, &exclusions);
    if !preamble.trim().is_empty() {
        let ambiguous = temporary_or_ambiguous_text(&preamble);
        let evidence = evidence_for_visible_range(
            document,
            text,
            0..preamble_end,
            &exclusions,
            "instruction",
            &[],
        )?;
        candidates.push(candidate(
            CaptureMemoryDraft {
                memory_type: MemoryType::Procedure,
                lane: MemoryLane::Procedural,
                title: "Repository instructions".to_owned(),
                body: preamble.trim().to_owned(),
                scope: scope.clone(),
                tags: vec!["agent-instructions".to_owned()],
            },
            evidence,
            extractor,
            if ambiguous {
                MemoryDestination::NeedsReview
            } else {
                MemoryDestination::Repo
            },
            if ambiguous {
                OkfProposalSensitivity::Unknown
            } else {
                OkfProposalSensitivity::RepoSafe
            },
            if ambiguous {
                "temporary_or_ambiguous_instruction_requires_review"
            } else {
                "explicit_instruction_file_preamble"
            },
            if ambiguous {
                "instruction_sharing_or_lifetime_is_ambiguous"
            } else {
                "explicit_repo_instruction_file_passed_safeguards"
            },
        )?);
    }

    for section in sections {
        check_planning_control(control)?;
        let heading_end = masked[section.start..section.direct_end]
            .find('\n')
            .map(|offset| section.start + offset + 1)
            .unwrap_or(section.direct_end);
        let body = visible_text(text, heading_end..section.direct_end, &exclusions);
        if body.trim().is_empty() {
            continue;
        }
        let (memory_type, lane, mut destination, mut sensitivity, section_kind, title) =
            match section.kind {
                Some((memory_type, lane, destination, sensitivity, section_kind)) => (
                    memory_type,
                    lane,
                    destination,
                    sensitivity,
                    format!("instruction_{section_kind}"),
                    section.title.clone(),
                ),
                None => (
                    MemoryType::Procedure,
                    MemoryLane::Procedural,
                    MemoryDestination::Repo,
                    OkfProposalSensitivity::RepoSafe,
                    "instruction".to_owned(),
                    section.title.clone(),
                ),
            };
        let ambiguous =
            temporary_or_ambiguous(&section.heading_path) || temporary_or_ambiguous_text(&body);
        if ambiguous {
            destination = MemoryDestination::NeedsReview;
            sensitivity = OkfProposalSensitivity::Unknown;
        }
        let evidence = evidence_for_visible_range(
            document,
            text,
            section.start..section.direct_end,
            &exclusions,
            &section_kind,
            &section.heading_path,
        )?;
        candidates.push(candidate(
            CaptureMemoryDraft {
                memory_type,
                lane,
                title,
                body: body.trim().to_owned(),
                scope: scope.clone(),
                tags: vec!["agent-instructions".to_owned()],
            },
            evidence,
            extractor,
            destination,
            sensitivity,
            if ambiguous {
                "temporary_or_ambiguous_instruction_requires_review"
            } else {
                "deterministic_instruction_section"
            },
            if ambiguous {
                "instruction_sharing_or_lifetime_is_ambiguous"
            } else {
                "explicit_repo_instruction_file_passed_safeguards"
            },
        )?);
    }

    if candidates.is_empty() && exclusions.is_empty() {
        diagnostics.push(CaptureDiagnostic {
            code: "unsupported_instruction_content".to_owned(),
            source_id: Some(document.request.source_id.clone()),
            line: Some(1),
        });
    }
    if !exclusions.is_empty() {
        diagnostics.push(CaptureDiagnostic {
            code: "generated_instruction_block_excluded".to_owned(),
            source_id: Some(document.request.source_id.clone()),
            line: Some(line_number_at(text, exclusions[0].start)),
        });
    }
    Ok(CaptureExtraction {
        candidates,
        diagnostics,
    })
}

fn generated_ranges(text: &str) -> Result<Vec<Range<usize>>> {
    let mut starts = Vec::new();
    let mut ends = Vec::new();
    for line in source_lines(text) {
        match line.logical.trim() {
            MEMZOI_START => starts.push(line),
            MEMZOI_END => ends.push(line),
            _ => {}
        }
    }
    if starts.is_empty() && ends.is_empty() {
        return Ok(Vec::new());
    }
    if starts.len() != 1 || ends.len() != 1 || starts[0].start >= ends[0].start {
        bail!("instruction source contains malformed Memzoi generated markers");
    }
    Ok(std::iter::once(starts[0].start..ends[0].end).collect())
}

fn mask_ranges(text: &str, ranges: &[Range<usize>]) -> String {
    let mut bytes = text.as_bytes().to_vec();
    for range in ranges {
        for byte in &mut bytes[range.clone()] {
            if *byte != b'\n' && *byte != b'\r' {
                *byte = b' ';
            }
        }
    }
    String::from_utf8(bytes).expect("masking UTF-8 with ASCII spaces preserves UTF-8")
}

fn visible_text(text: &str, range: Range<usize>, exclusions: &[Range<usize>]) -> String {
    visible_ranges(range, exclusions)
        .into_iter()
        .map(|range| text[range].trim())
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join("\n")
}

fn evidence_for_visible_range(
    document: &CaptureSourceDocument,
    text: &str,
    range: Range<usize>,
    exclusions: &[Range<usize>],
    section_kind: &str,
    heading_path: &[String],
) -> Result<Vec<super::super::CaptureEvidence>> {
    let mut evidence = Vec::new();
    for range in visible_ranges(range, exclusions) {
        let Some(range) = trim_range(text, range) else {
            continue;
        };
        let mut item = evidence_for(
            &document.request,
            &document.snapshot,
            text,
            EvidenceLocation {
                start: range.start,
                end: range.end,
                line_start: line_number_at(text, range.start),
                section_kind,
                heading_path,
            },
        )?;
        for item in &mut item {
            item.semantic_location = Some(CaptureSemanticLocation::Instruction);
        }
        evidence.extend(item);
    }
    if evidence.is_empty() {
        bail!("instruction candidate has no non-generated evidence");
    }
    Ok(evidence)
}

fn visible_ranges(range: Range<usize>, exclusions: &[Range<usize>]) -> Vec<Range<usize>> {
    let mut ranges = vec![range];
    for exclusion in exclusions {
        let mut next = Vec::new();
        for current in ranges {
            if exclusion.end <= current.start || exclusion.start >= current.end {
                next.push(current);
                continue;
            }
            if current.start < exclusion.start {
                next.push(current.start..exclusion.start);
            }
            if exclusion.end < current.end {
                next.push(exclusion.end..current.end);
            }
        }
        ranges = next;
    }
    ranges
}

fn trim_range(text: &str, range: Range<usize>) -> Option<Range<usize>> {
    let slice = &text[range.clone()];
    let leading = slice.len() - slice.trim_start().len();
    let trailing = slice.len() - slice.trim_end().len();
    let start = range.start + leading;
    let end = range.end.saturating_sub(trailing);
    (start < end).then_some(start..end)
}

fn instruction_scope(document: &CaptureSourceDocument) -> CaptureScope {
    let path = document.request.locator.project_path().unwrap_or_default();
    let parent = Path::new(path)
        .parent()
        .and_then(Path::to_str)
        .filter(|parent| !parent.is_empty())
        .map(str::to_owned);
    CaptureScope {
        kind: ScopeKind::Repo,
        id: None,
        paths: parent.into_iter().collect(),
    }
}

fn temporary_or_ambiguous(heading_path: &[String]) -> bool {
    heading_path
        .iter()
        .any(|heading| contains_instruction_review_marker(heading))
}

fn temporary_or_ambiguous_text(text: &str) -> bool {
    text.lines().any(contains_instruction_review_marker)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn marker_mask_keeps_secret_scannable() {
        let source = format!("{MEMZOI_START}\npassword = hunter2\n{MEMZOI_END}\n");
        let masked = mask_generated_markers_for_scan(source.as_bytes());
        let rendered = String::from_utf8(masked).unwrap();
        assert!(!rendered.contains(MEMZOI_START));
        assert!(rendered.contains("password = hunter2"));
    }

    #[test]
    fn malformed_markers_are_rejected() {
        let error = generated_ranges(&format!("{MEMZOI_END}\n{MEMZOI_START}\n")).unwrap_err();
        assert!(error.to_string().contains("malformed"));
    }

    #[test]
    fn ambiguity_markers_match_complete_words_inside_headings() {
        for heading in [
            "Temporary notes",
            "Private instructions",
            "Current-task overrides",
            "Local-only guidance",
        ] {
            assert!(temporary_or_ambiguous(&[heading.to_owned()]), "{heading}");
        }
        for heading in ["Temporarily stable", "Privateer workflow"] {
            assert!(!temporary_or_ambiguous(&[heading.to_owned()]), "{heading}");
        }
    }
}
